site_name: ğŸ—ƒï¸ Manual do UsuÃ¡rio SGD
nav:
  -  ğŸ  InÃ­cio: index.md 
  -  ğŸ›¡ï¸ SeguranÃ§a:
      - ğŸ‘¤ Cadastro de usuÃ¡rios: seguranca/cadastro.md
      - ğŸ‘¥ Grupos de UsuÃ¡rios: seguranca/grupo.md
      - ğŸ“± AplicaÃ§Ãµes : seguranca/aplicacoes.md
      - ğŸ—ƒï¸ Grupo de AplicaÃ§Ãµes : seguranca/grupo_aplica.md
      - ğŸ”—ğŸ‘¤ UsuÃ¡rios para Grupo : seguranca/usuario_grupo.md
      - ğŸ”—ğŸ“±Aplicativos para Grupo : seguranca/aplica_grupo.md
      - ğŸ“ Regras de NegÃ³cio : seguranca/regras.md
      - ğŸ”’ğŸ“±APPS x PermissÃ£o : seguranca/apps.md
      - ğŸ“« Envio Email :
        - ğŸ“§ Contas de Email : seguranca/contas.md
        - ğŸ””Tipos notificaÃ§Ãµes : seguranca/tipo.md
        - ğŸ™‹ Pessoas por NotificaÃ§Ã£o : seguranca/pessoas.md
      - ğŸ§‘ğŸ»â€ğŸ’» UsuÃ¡rios Logados : seguranca/usuarios_log.md
      - ğŸ’» Log do Sistema : seguranca/log.md
      - ğŸ” Alterar Senha : seguranca/senha.md
      - ğŸ—‚ï¸ Versionamento :
        - ğŸ“ Registrar AlteraÃ§Ãµes : seguranca/registrar.md
        - ğŸ”„ Versionar : seguranca/versionar.md
        - ğŸ“œ HistÃ³rico de VersÃµes : seguranca/historico.md
      - ğŸ“© SMS : seguranca/sms.md
  -  ğŸ‘·â€â™‚ï¸ Operacional: operacional.md
  -  ğŸ©º SaÃºde e SeguranÃ§a: saude-seguranca.md
  -  ğŸ¦ Monitoria: monitoria.md
  -  ğŸ‘¨â€ğŸ’¼ RH/DP: rh-dp.md
  -  ğŸ“‹ SGI:
      - ğŸ“‘ HomologaÃ§Ã£o de produdos : sgi/homologacao.md
      - ğŸ“œ Lista Maestra :
        - ğŸ—‚ï¸ Cadastro : sgi/cadastro_mestre.md
        - ğŸ“Š Relatorio : sgi/relata_mestre.md
        - ğŸ”§ Cadastros Auxiliares : 
          - ğŸ“„ Cad. Documentos : sgi/cadastro_doc.md
          - ğŸŒ Cad. ArÃ©a : sgi/cadastro_area.md
          - ğŸ†” Cad. IndentificaÃ§Ã£o: sgi/cadastro_id.md
          - ğŸ›¡ï¸ Cad. ProteÃ§Ã£o : sgi/cadastro_prot.md
      - ğŸ—’ï¸ Lista de PresenÃ§a :
        - âœï¸ Registrar : sgi/registrar.md
        - ğŸ“† Cronograma de Treinamento : sgi/cronograma.md
        - ğŸ“ŒTitulo : 
          - ğŸ—‚ï¸ Cadastro : sgi/cadastro.md
          - ğŸ“‘ Relatorio : sgi/relata_titulo.md
        - ğŸ“Š RelatÃ³rios : 
          - ğŸ—‚ï¸ğŸ“‹ Por Registro : sgi/relata_registro.md
          - ğŸ‘¨â€ğŸ« Por Instrutor : sgi/relata_instrutor.md
          - ğŸ§‘â€ğŸ¤â€ğŸ§‘ Por Participante : sgi/relata_participante.md
          - ğŸ’¬ Feedback de Treinamento : sgi/feedback.md
        - âœï¸ Assinaturas Gerais: SGD/assinatura_gerais.md
  -  ğŸ“¦ Almoxarifado: almoxarifado.md
  -  ğŸ“Š Indicadores: indicadores.md
  -  ğŸ“¢ ComunicaÃ§Ã£o: comunicacao.md
  -  ğŸ§ HelpDesk: helpdesk.md
  -  ğŸ‘©â€ğŸ’» SGD:
      - ğŸ“¡ Radar de AÃ§Ãµes: SGD/radar_acoes.md
      - ğŸ”‘ Alterar Senha: SGD/alterar_senha.md
      - ğŸ¨ Alterar Tema: SGD/alterar_tema.md
      - âœï¸ Assinaturas Gerais: SGD/assinatura_gerais.md
      - â˜ï¸ Coletar Biometria: SGD/coletar_biometria.md
      - ğŸ‘¤ğŸ“·Coletar Biometria Facial: SGD/coletar_biometria_facial.md
      - ğŸ›¡ï¸ Biometria: SGD/biometria.md
      - ğŸšª Meus Acessos: SGD/meus_acessos.md
      - ğŸ“‹â—PendÃªncias: SGD/pendencias.md
      - ğŸ”“ Sair: SGD/sair.md
theme: 
  name: dracula
  favicon: img/favicon.ico
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - content.full_width
extra_css:
  - css/custom.css
extra_javascript:
  - assets/js/lightbox-plus-jquery.js
  - assets/js/checklists.js
markdown_extensions:
  - attr_list
  - full_yaml_metadata
  - toc:
      permalink: false
      title:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
plugins:
  - search
